"""current_schema

Revision ID: 0003_current_schema
Revises: 0002_add_customer_gender
Create Date: 2026-05-20 21:39:06.138088+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0003_current_schema'
down_revision: Union[str, None] = '0002_add_customer_gender'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('next_run_time', sa.Float(precision=25), nullable=True),
    sa.Column('job_state', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nango_connection_id', sa.String(length=255), nullable=False),
    sa.Column('shopify_store_domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tracking_installed', sa.Boolean(), nullable=False),
    sa.Column('tracking_installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_nango_connection_id'), 'stores', ['nango_connection_id'], unique=True)
    op.create_index(op.f('ix_stores_shopify_store_domain'), 'stores', ['shopify_store_domain'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shopify_customer_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shopify_customer_id', name='uq_customers_store_shopify_id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_shopify_customer_id'), 'customers', ['shopify_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_store_id'), 'customers', ['store_id'], unique=False)
    op.create_table('outfit_image_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=128), nullable=False),
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('product_ids_json', sa.JSON(), nullable=False),
    sa.Column('embedding_json', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('avg_engagement_score', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_image_cache_cache_key'), 'outfit_image_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_outfit_image_cache_id'), 'outfit_image_cache', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_image_cache_store_id'), 'outfit_image_cache', ['store_id'], unique=False)
    op.create_index('ix_outfit_image_cache_store_trigger', 'outfit_image_cache', ['store_id', 'trigger_reason'], unique=False)
    op.create_index(op.f('ix_outfit_image_cache_trigger_reason'), 'outfit_image_cache', ['trigger_reason'], unique=False)
    op.create_index('ix_outfit_image_cache_updated_at', 'outfit_image_cache', ['updated_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shopify_product_id', name='uq_products_store_shopify_id')
    )
    op.create_index(op.f('ix_products_handle'), 'products', ['handle'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_shopify_product_id'), 'products', ['shopify_product_id'], unique=False)
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('products_synced', sa.Integer(), nullable=False),
    sa.Column('customers_synced', sa.Integer(), nullable=False),
    sa.Column('orders_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_id'), 'sync_runs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_runs_store_id'), 'sync_runs', ['store_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('dominant_aesthetic', sa.String(length=255), nullable=True),
    sa.Column('color_palette', sa.Text(), nullable=True),
    sa.Column('preference_dimensions_json', sa.JSON(), nullable=False),
    sa.Column('conversation_history_json', sa.JSON(), nullable=False),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'customer_id', name='uq_customer_profiles_store_customer')
    )
    op.create_index('ix_customer_profiles_customer_id', 'customer_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.create_index('ix_customer_profiles_store_id', 'customer_profiles', ['store_id'], unique=False)
    op.create_table('generated_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('product_title', sa.String(length=500), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_messages_customer_id', 'generated_messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_generated_messages_id'), 'generated_messages', ['id'], unique=False)
    op.create_index('ix_generated_messages_status', 'generated_messages', ['status'], unique=False)
    op.create_index('ix_generated_messages_store_customer_product_status', 'generated_messages', ['store_id', 'customer_id', 'product_id', 'status'], unique=False)
    op.create_index('ix_generated_messages_store_id', 'generated_messages', ['store_id'], unique=False)
    op.create_index('ix_generated_messages_store_status', 'generated_messages', ['store_id', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=64), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'shopify_order_id', name='uq_orders_store_shopify_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_delivered_at'), 'orders', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_orders_fulfillment_status'), 'orders', ['fulfillment_status'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_shopify_order_id'), 'orders', ['shopify_order_id'], unique=False)
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.create_table('retention_campaign_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'customer_id', 'campaign_type', name='uq_campaign_state_store_customer_campaign')
    )
    op.create_index('ix_campaign_states_status', 'retention_campaign_states', ['status'], unique=False)
    op.create_index('ix_campaign_states_store_campaign', 'retention_campaign_states', ['store_id', 'campaign_type'], unique=False)
    op.create_index(op.f('ix_retention_campaign_states_campaign_type'), 'retention_campaign_states', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_retention_campaign_states_customer_id'), 'retention_campaign_states', ['customer_id'], unique=False)
    op.create_index(op.f('ix_retention_campaign_states_id'), 'retention_campaign_states', ['id'], unique=False)
    op.create_index(op.f('ix_retention_campaign_states_status'), 'retention_campaign_states', ['status'], unique=False)
    op.create_index(op.f('ix_retention_campaign_states_store_id'), 'retention_campaign_states', ['store_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_first_time', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_sessions_session_id')
    )
    op.create_index(op.f('ix_sessions_customer_id'), 'sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessions_store_id'), 'sessions', ['store_id'], unique=False)
    op.create_index('ix_sessions_store_last_seen', 'sessions', ['store_id', 'last_seen_at'], unique=False)
    op.create_table('buyer_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('first_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_id', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('first_order_summary', sa.Text(), nullable=True),
    sa.Column('last_order_summary', sa.Text(), nullable=True),
    sa.Column('wardrobe_summary', sa.Text(), nullable=True),
    sa.Column('interest_summary', sa.Text(), nullable=True),
    sa.Column('memory_summary', sa.Text(), nullable=True),
    sa.Column('favorite_categories', sa.Text(), nullable=True),
    sa.Column('favorite_colors', sa.Text(), nullable=True),
    sa.Column('style_tags', sa.Text(), nullable=True),
    sa.Column('price_band', sa.String(length=64), nullable=True),
    sa.Column('order_history_json', sa.JSON(), nullable=False),
    sa.Column('wardrobe_items_json', sa.JSON(), nullable=False),
    sa.Column('recent_interests_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['last_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'customer_id', name='uq_buyer_memory_store_customer')
    )
    op.create_index('ix_buyer_memory_customer_id', 'buyer_memory', ['customer_id'], unique=False)
    op.create_index(op.f('ix_buyer_memory_id'), 'buyer_memory', ['id'], unique=False)
    op.create_index('ix_buyer_memory_store_id', 'buyer_memory', ['store_id'], unique=False)
    op.create_index('ix_buyer_memory_updated_at', 'buyer_memory', ['updated_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_customer_id'), 'events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_product_id'), 'events', ['product_id'], unique=False)
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_store_id'), 'events', ['store_id'], unique=False)
    op.create_index('ix_events_store_timestamp', 'events', ['store_id', 'timestamp'], unique=False)
    op.create_index('ix_events_store_type', 'events', ['store_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('return_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shopify_refund_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_refunds_created_at'), 'return_refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_return_refunds_customer_id'), 'return_refunds', ['customer_id'], unique=False)
    op.create_index(op.f('ix_return_refunds_id'), 'return_refunds', ['id'], unique=False)
    op.create_index(op.f('ix_return_refunds_order_id'), 'return_refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_refunds_shopify_refund_id'), 'return_refunds', ['shopify_refund_id'], unique=False)
    op.create_index(op.f('ix_return_refunds_status'), 'return_refunds', ['status'], unique=False)
    op.create_index('ix_return_refunds_store_customer', 'return_refunds', ['store_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_return_refunds_store_id'), 'return_refunds', ['store_id'], unique=False)
    op.create_table('generated_outfit_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('buyer_memory_id', sa.Integer(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('task_status', sa.String(length=64), nullable=True),
    sa.Column('task_progress', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('recommended_products_json', sa.JSON(), nullable=False),
    sa.Column('reference_image_urls_json', sa.JSON(), nullable=False),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_memory_id'], ['buyer_memory.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_outfit_images_customer_id', 'generated_outfit_images', ['customer_id'], unique=False)
    op.create_index(op.f('ix_generated_outfit_images_id'), 'generated_outfit_images', ['id'], unique=False)
    op.create_index('ix_generated_outfit_images_order_id', 'generated_outfit_images', ['order_id'], unique=False)
    op.create_index('ix_generated_outfit_images_status', 'generated_outfit_images', ['status'], unique=False)
    op.create_index('ix_generated_outfit_images_store_id', 'generated_outfit_images', ['store_id'], unique=False)
    op.create_index('ix_generated_outfit_images_store_status', 'generated_outfit_images', ['store_id', 'status'], unique=False)
    op.create_index(op.f('ix_generated_outfit_images_task_id'), 'generated_outfit_images', ['task_id'], unique=False)
    op.create_table('retention_send_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_type', sa.String(length=128), nullable=False),
    sa.Column('trigger_reason', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('outfit_image_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['outfit_image_id'], ['generated_outfit_images.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retention_send_logs_campaign', 'retention_send_logs', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_campaign_type'), 'retention_send_logs', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_customer_id'), 'retention_send_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_id'), 'retention_send_logs', ['id'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_provider_message_id'), 'retention_send_logs', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_sent_at'), 'retention_send_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_status'), 'retention_send_logs', ['status'], unique=False)
    op.create_index('ix_retention_send_logs_store_customer', 'retention_send_logs', ['store_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_retention_send_logs_store_id'), 'retention_send_logs', ['store_id'], unique=False)
    op.create_table('customer_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('send_log_id', sa.Integer(), nullable=True),
    sa.Column('inbound_text', sa.Text(), nullable=False),
    sa.Column('extracted_preferences_json', sa.JSON(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['send_log_id'], ['retention_send_logs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_replies_created_at', 'customer_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_replies_customer_id'), 'customer_replies', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_replies_id'), 'customer_replies', ['id'], unique=False)
    op.create_index('ix_customer_replies_store_customer', 'customer_replies', ['store_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_customer_replies_store_id'), 'customer_replies', ['store_id'], unique=False)
    op.create_table('email_engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('send_log_id', sa.Integer(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('campaign_type', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['send_log_id'], ['retention_send_logs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_engagement_campaign', 'email_engagement', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_email_engagement_campaign_type'), 'email_engagement', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_email_engagement_customer_id'), 'email_engagement', ['customer_id'], unique=False)
    op.create_index(op.f('ix_email_engagement_event_type'), 'email_engagement', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_engagement_id'), 'email_engagement', ['id'], unique=False)
    op.create_index(op.f('ix_email_engagement_provider_message_id'), 'email_engagement', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_engagement_send_log_id'), 'email_engagement', ['send_log_id'], unique=False)
    op.create_index('ix_email_engagement_store_customer', 'email_engagement', ['store_id', 'customer_id'], unique=False)
    op.create_index('ix_email_engagement_store_event_time', 'email_engagement', ['store_id', 'event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_email_engagement_store_id'), 'email_engagement', ['store_id'], unique=False)
    op.create_index(op.f('ix_email_engagement_timestamp'), 'email_engagement', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_engagement_timestamp'), table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_store_id'), table_name='email_engagement')
    op.drop_index('ix_email_engagement_store_event_time', table_name='email_engagement')
    op.drop_index('ix_email_engagement_store_customer', table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_send_log_id'), table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_provider_message_id'), table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_id'), table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_event_type'), table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_customer_id'), table_name='email_engagement')
    op.drop_index(op.f('ix_email_engagement_campaign_type'), table_name='email_engagement')
    op.drop_index('ix_email_engagement_campaign', table_name='email_engagement')
    op.drop_table('email_engagement')
    op.drop_index(op.f('ix_customer_replies_store_id'), table_name='customer_replies')
    op.drop_index('ix_customer_replies_store_customer', table_name='customer_replies')
    op.drop_index(op.f('ix_customer_replies_id'), table_name='customer_replies')
    op.drop_index(op.f('ix_customer_replies_customer_id'), table_name='customer_replies')
    op.drop_index('ix_customer_replies_created_at', table_name='customer_replies')
    op.drop_table('customer_replies')
    op.drop_index(op.f('ix_retention_send_logs_store_id'), table_name='retention_send_logs')
    op.drop_index('ix_retention_send_logs_store_customer', table_name='retention_send_logs')
    op.drop_index(op.f('ix_retention_send_logs_status'), table_name='retention_send_logs')
    op.drop_index(op.f('ix_retention_send_logs_sent_at'), table_name='retention_send_logs')
    op.drop_index(op.f('ix_retention_send_logs_provider_message_id'), table_name='retention_send_logs')
    op.drop_index(op.f('ix_retention_send_logs_id'), table_name='retention_send_logs')
    op.drop_index(op.f('ix_retention_send_logs_customer_id'), table_name='retention_send_logs')
    op.drop_index(op.f('ix_retention_send_logs_campaign_type'), table_name='retention_send_logs')
    op.drop_index('ix_retention_send_logs_campaign', table_name='retention_send_logs')
    op.drop_table('retention_send_logs')
    op.drop_index(op.f('ix_generated_outfit_images_task_id'), table_name='generated_outfit_images')
    op.drop_index('ix_generated_outfit_images_store_status', table_name='generated_outfit_images')
    op.drop_index('ix_generated_outfit_images_store_id', table_name='generated_outfit_images')
    op.drop_index('ix_generated_outfit_images_status', table_name='generated_outfit_images')
    op.drop_index('ix_generated_outfit_images_order_id', table_name='generated_outfit_images')
    op.drop_index(op.f('ix_generated_outfit_images_id'), table_name='generated_outfit_images')
    op.drop_index('ix_generated_outfit_images_customer_id', table_name='generated_outfit_images')
    op.drop_table('generated_outfit_images')
    op.drop_index(op.f('ix_return_refunds_store_id'), table_name='return_refunds')
    op.drop_index('ix_return_refunds_store_customer', table_name='return_refunds')
    op.drop_index(op.f('ix_return_refunds_status'), table_name='return_refunds')
    op.drop_index(op.f('ix_return_refunds_shopify_refund_id'), table_name='return_refunds')
    op.drop_index(op.f('ix_return_refunds_order_id'), table_name='return_refunds')
    op.drop_index(op.f('ix_return_refunds_id'), table_name='return_refunds')
    op.drop_index(op.f('ix_return_refunds_customer_id'), table_name='return_refunds')
    op.drop_index(op.f('ix_return_refunds_created_at'), table_name='return_refunds')
    op.drop_table('return_refunds')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index('ix_events_store_type', table_name='events')
    op.drop_index('ix_events_store_timestamp', table_name='events')
    op.drop_index(op.f('ix_events_store_id'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_index(op.f('ix_events_product_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_customer_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_buyer_memory_updated_at', table_name='buyer_memory')
    op.drop_index('ix_buyer_memory_store_id', table_name='buyer_memory')
    op.drop_index(op.f('ix_buyer_memory_id'), table_name='buyer_memory')
    op.drop_index('ix_buyer_memory_customer_id', table_name='buyer_memory')
    op.drop_table('buyer_memory')
    op.drop_index('ix_sessions_store_last_seen', table_name='sessions')
    op.drop_index(op.f('ix_sessions_store_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_customer_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_retention_campaign_states_store_id'), table_name='retention_campaign_states')
    op.drop_index(op.f('ix_retention_campaign_states_status'), table_name='retention_campaign_states')
    op.drop_index(op.f('ix_retention_campaign_states_id'), table_name='retention_campaign_states')
    op.drop_index(op.f('ix_retention_campaign_states_customer_id'), table_name='retention_campaign_states')
    op.drop_index(op.f('ix_retention_campaign_states_campaign_type'), table_name='retention_campaign_states')
    op.drop_index('ix_campaign_states_store_campaign', table_name='retention_campaign_states')
    op.drop_index('ix_campaign_states_status', table_name='retention_campaign_states')
    op.drop_table('retention_campaign_states')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_shopify_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_fulfillment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivered_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_generated_messages_store_status', table_name='generated_messages')
    op.drop_index('ix_generated_messages_store_id', table_name='generated_messages')
    op.drop_index('ix_generated_messages_store_customer_product_status', table_name='generated_messages')
    op.drop_index('ix_generated_messages_status', table_name='generated_messages')
    op.drop_index(op.f('ix_generated_messages_id'), table_name='generated_messages')
    op.drop_index('ix_generated_messages_customer_id', table_name='generated_messages')
    op.drop_table('generated_messages')
    op.drop_index('ix_customer_profiles_store_id', table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.drop_index('ix_customer_profiles_customer_id', table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_sync_runs_store_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_index(op.f('ix_products_shopify_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_handle'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_outfit_image_cache_updated_at', table_name='outfit_image_cache')
    op.drop_index(op.f('ix_outfit_image_cache_trigger_reason'), table_name='outfit_image_cache')
    op.drop_index('ix_outfit_image_cache_store_trigger', table_name='outfit_image_cache')
    op.drop_index(op.f('ix_outfit_image_cache_store_id'), table_name='outfit_image_cache')
    op.drop_index(op.f('ix_outfit_image_cache_id'), table_name='outfit_image_cache')
    op.drop_index(op.f('ix_outfit_image_cache_cache_key'), table_name='outfit_image_cache')
    op.drop_table('outfit_image_cache')
    op.drop_index(op.f('ix_customers_store_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_shopify_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_stores_shopify_store_domain'), table_name='stores')
    op.drop_index(op.f('ix_stores_nango_connection_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###
